using System.Text.Json.Serialization;

namespace JsonConverter
{
    public record Coordinates([property:JsonPropertyName("latitude")] double Latitude, [property:JsonPropertyName("longitude")] double Longitude);
    public record Headquarters([property:JsonPropertyName("address")] string Address, [property:JsonPropertyName("city")] string City, [property:JsonPropertyName("state")] string State, [property:JsonPropertyName("country")] string Country, [property:JsonPropertyName("coordinates")] Coordinates Coordinates);
    public record Company([property:JsonPropertyName("id")] string Id, [property:JsonPropertyName("name")] string Name, [property:JsonPropertyName("founded")] DateTime Founded, [property:JsonPropertyName("isPublic")] bool IsPublic, [property:JsonPropertyName("stockPrice")] double StockPrice, [property:JsonPropertyName("marketCap")] int MarketCap, [property:JsonPropertyName("activeMarkets")] IReadOnlyList<string> ActiveMarkets, [property:JsonPropertyName("headquarters")] Headquarters Headquarters);
    public record Deadlines([property:JsonPropertyName("start")] DateTime Start, [property:JsonPropertyName("end")] DateTime End);
    public record Projects([property:JsonPropertyName("id")] string Id, [property:JsonPropertyName("name")] string Name, [property:JsonPropertyName("status")] string Status, [property:JsonPropertyName("deadlines")] Deadlines Deadlines);
    public record _2023([property:JsonPropertyName("q1")] double Q1, [property:JsonPropertyName("q2")] double Q2, [property:JsonPropertyName("q3")] double Q3, [property:JsonPropertyName("q4")] double Q4);
    public record Performance([property:JsonPropertyName("2023")] _2023 _2023);
    public record Employees([property:JsonPropertyName("id")] string Id, [property:JsonPropertyName("firstName")] string FirstName, [property:JsonPropertyName("lastName")] string LastName, [property:JsonPropertyName("email")] string Email, [property:JsonPropertyName("role")] string Role, [property:JsonPropertyName("department")] string Department, [property:JsonPropertyName("startDate")] DateTime StartDate, [property:JsonPropertyName("salary")] int Salary, [property:JsonPropertyName("skills")] IReadOnlyList<string> Skills, [property:JsonPropertyName("projects")] IReadOnlyList<Projects> Projects, [property:JsonPropertyName("performance")] Performance Performance);
    public record Limitations([property:JsonPropertyName("maxUsers")] int MaxUsers, [property:JsonPropertyName("maxStorage")] string MaxStorage, [property:JsonPropertyName("maxRequests")] int MaxRequests);
    public record Features([property:JsonPropertyName("name")] string Name, [property:JsonPropertyName("isEnabled")] bool IsEnabled, [property:JsonPropertyName("limitations")] Limitations Limitations);
    public record Metrics([property:JsonPropertyName("activeUsers")] int ActiveUsers, [property:JsonPropertyName("uptime")] double Uptime, [property:JsonPropertyName("satisfaction")] double Satisfaction);
    public record Products([property:JsonPropertyName("id")] string Id, [property:JsonPropertyName("name")] string Name, [property:JsonPropertyName("version")] DateTime Version, [property:JsonPropertyName("price")] double Price, [property:JsonPropertyName("currency")] string Currency, [property:JsonPropertyName("isSubscription")] bool IsSubscription, [property:JsonPropertyName("features")] IReadOnlyList<Features> Features, [property:JsonPropertyName("metrics")] Metrics Metrics);
    public record Q1([property:JsonPropertyName("revenue")] int Revenue, [property:JsonPropertyName("expenses")] int Expenses, [property:JsonPropertyName("profit")] int Profit);
    public record Q2([property:JsonPropertyName("revenue")] int Revenue, [property:JsonPropertyName("expenses")] int Expenses, [property:JsonPropertyName("profit")] int Profit);
    public record Q3([property:JsonPropertyName("revenue")] int Revenue, [property:JsonPropertyName("expenses")] int Expenses, [property:JsonPropertyName("profit")] int Profit);
    public record Q4([property:JsonPropertyName("revenue")] int Revenue, [property:JsonPropertyName("expenses")] int Expenses, [property:JsonPropertyName("profit")] int Profit);
    public record Quarters([property:JsonPropertyName("q1")] Q1 Q1, [property:JsonPropertyName("q2")] Q2 Q2, [property:JsonPropertyName("q3")] Q3 Q3, [property:JsonPropertyName("q4")] Q4 Q4);
    public record CurrentYear([property:JsonPropertyName("revenue")] int Revenue, [property:JsonPropertyName("expenses")] int Expenses, [property:JsonPropertyName("profit")] int Profit, [property:JsonPropertyName("quarters")] Quarters Quarters);
    public record Financials([property:JsonPropertyName("currentYear")] CurrentYear CurrentYear);
    public record Debug([property:JsonPropertyName("enabled")] bool Enabled, [property:JsonPropertyName("level")] string Level, [property:JsonPropertyName("retentionDays")] int RetentionDays);
    public record Metadata([property:JsonPropertyName("lastUpdated")] DateTime LastUpdated, [property:JsonPropertyName("version")] string Version, [property:JsonPropertyName("environment")] string Environment, [property:JsonPropertyName("tags")] IReadOnlyList<string> Tags, [property:JsonPropertyName("debug")] Debug Debug);
    public record Root([property:JsonPropertyName("company")] Company Company, [property:JsonPropertyName("employees")] IReadOnlyList<Employees> Employees, [property:JsonPropertyName("products")] IReadOnlyList<Products> Products, [property:JsonPropertyName("financials")] Financials Financials, [property:JsonPropertyName("metadata")] Metadata Metadata);
}